### ISSUE TITLE
S'hauria de migrar a antdv5 ?

### ISSUE THREAD

**Issue by ecarreras** [gisce/react-formiga-table#5]
He vist que com a dependència (dev) té antdv4, s'hauria de passar a v5?

**Comment by mguellsegarra** [comment]
@ecarreras 

Bueno, al final la llibreria no fa servir `ant` realment, només té `ant` com a `devDependencies` per a poder utilitzar-ho a l'Storybook, i aquí sí que es podria passar a `antdv5`.

Penso que es pot fer bastant ràpid, li faig una ullada

**Comment by mguellsegarra** [comment]
Fet! 💪
