### ISSUE TITLE
Pensar si es pot fer servir tanStack table

### ISSUE THREAD

**Issue by ecarreras** [gisce/react-formiga-table#9]
https://tanstack.com/table/v8

**Comment by mguellsegarra** [comment]
@ecarreras 

De fet, vam crear aquesta llibreria inspirant-nos amb tanstack table v7, nosé si ho recordes (https://github.com/gisce/webclient/issues/78) 

Vaig fer servir la idea que tenien ells a la seva lib, aprofitant molt de codi. Hi havia parts que necessitavem modificar, i al final vaig pensar que era millor tenir nosaltres el control encara que molta part fos heredada de tanstackv7

De totes formes, si trobes funcionalitats interessants al tanstack v8, es poden mirar d'implementar. O directament si veus millor fer servir la v8?

**Comment by ecarreras** [comment]
Més que res, m'agradaria analitzar si una llibrería com la de tanstack té problemes al mostrar molts registres, ja que amb el webclient tenim problemes quan la gent amplia el límit de registres
